
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-migration
  namespace: refarch-example

data:
  01_init-realm.yml: |
    id: init realm
    author: Default
    changes:
      - addRealm:
          name: local_realm

  02_add-clients.yml: |
    id: add and configure local client
    author: Default
    realm: local_realm
    changes:
      - addSimpleClient:
          clientId: local
          secret: client_secret
          publicClient: false
          redirectUris:
            - http://*
            - https://*

      # Disable fullScope to only return userInfo
      # of requested client
      - updateClient:
          clientId: local
          fullScopeAllowed: false

      # Add roles to user-info
      - deleteClientScopeMapper:
          clientScopeName: roles
          name: client roles

      - addClientScopeMapper:
          clientScopeName: roles
          name: client roles
          protocolMapper: oidc-usermodel-client-role-mapper
          config:
            "multivalued": "true"
            "userinfo.token.claim": "true"
            "id.token.claim": "false"
            "access.token.claim": "true"
            "claim.name": "resource_access.$${client_id}.roles"
            "jsonType.label": "String"

  03_add-roles.yml: |
    id: add roles
    author: Default
    realm: local_realm
    changes:
      - addRole:
          name: admin
          description: Admin role for our test project
          clientRole: true
          clientId: local
          composite: false

      - addRole:
          name: student
          description: Default student role for our test project
          clientRole: true
          clientId: local
          composite: false

      - addRole:
          name: fachstudent
          description: Student role that can add Zeitgutschriften
          clientRole: true
          clientId: local
          composite: false

  04_add-users.yml: |
    id: add users
    author: Default
    realm: local_realm
    changes:
      - addUser:
          name: 100
          lastName: Mustermann
          firstName: Max
          enabled: true
          emailVerified: true
          email: none0@none

      - updateUserPassword:
          name: 100
          password: test

      - addUser:
          name: 101
          lastName: Huber
          firstName: Ernst
          enabled: true
          emailVerified: true
          email: none1@none

      - updateUserPassword:
          name: 101
          password: test

      - addUser:
          name: 102
          lastName: Müller
          firstName: Jonas
          enabled: true
          emailVerified: true
          email: none2@none

      - updateUserPassword:
          name: 102
          password: test

  05_assign-roles.yml: |
    id: assign roles to users
    author: Default
    realm: local_realm
    changes:
      - assignRole:
          user: 100
          role: admin
          clientId: local

      - assignRole:
          user: 101
          role: student
          clientId: local

      - assignRole:
          user: 102
          role: fachstudent
          clientId: local

  06_local-audience.yml: |
    id: configure local audience
    author: Default
    realm: local_realm
    changes:
      - addClientScope:
          name: local_audience
          description: Add local to audience claim
          protocolMappers:
            - name: local_audience
              protocol: openid-connect
              protocolMapper: oidc-audience-mapper
              config:
                access.token.claim: "true"
                id.token.claim: "true"
                included.client.audience: "local"
                included.custom.audience: ""

      - assignDefaultClientScope:
          clientId: local
          clientScopeName: local_audience

  keycloak-changelog.yml: |
    includes:
      - path: 01_init-realm.yml
      - path: 02_add-clients.yml
      - path: 03_add-roles.yml
      - path: 04_add-users.yml
      - path: 05_assign-roles.yml
      - path: 06_local-audience.yml
