create table studiengang (
    studiengang_nr int GENERATED BY DEFAULT AS IDENTITY (START WITH 100) not null,
    name varchar(255) not null,
    primary key (studiengang_nr)
);

create table student (
    student_id int generated by default as identity (start with 100) not null,
    vorname varchar(255) not null,
    nachname varchar(255) not null,
    primary key (student_id)
);

create table studiengang_student (
    student_id int references student(student_id) not null,
    studiengang_nr int references studiengang(studiengang_nr) not null,
    primary key (student_id, studiengang_nr)
);

create table praktikum (
    beginn_datum date not null,
    ende_datum date not null,
    student_id int references student(student_id) not null unique,
    wochenarbeitszeit int not null,
    benoetigte_wochen int not null,
    primary key (student_id)
);

create table taetigkeitenblock (
    tag date not null,
    beginn_Zeit time not null,
    ende_Zeit time not null,
    student_id int not null,
    foreign key (student_id) references praktikum(student_id),
    homeoffice boolean not null,
    primary key (tag, beginn_Zeit, ende_Zeit, student_id)
);

create table zeitgutschrift (
    id int generated by default as identity not null,
    tag date not null,
    menge_minuten int not null,
    grund varchar(255) not null,
    praktikum_student_id int not null,
    foreign key (praktikum_student_id) references praktikum(student_id),
    primary key (id)
);